import Head from "next/head";
import Image from "next/image";

import { getOrderedCollection } from "../src/contentful";

import Header from "../src/components/header";

import Logo from "../src/components/svg/logo";

import styles from "../styles/Home.module.scss";

export const getStaticProps = async () => {
  return {
    props: await getOrderedCollection("page", "sys.createdAt")
  };
};

const Home = props => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>
          <i>placeholders for future content:</i>
        </p>
        <h2>
          <i>Shorter &quot;about me&quot; or intro blurb?</i>
        </h2>
        <h1>What is Myofunctional Therapy?</h1>
        <h1>How does it work?</h1>
        <h1>Blog</h1>
      </main>
    </div>
  );
};

export default Home;
