import Head from "next/head";
import Image from "next/image";

import { getOrderedCollection } from "../src/contentful";

import Header from "../src/components/header";

import Logo from '../src/components/svg/logo'

import styles from "../styles/Home.module.scss";

export const getStaticProps = async () => {
  return {
    props: await getOrderedCollection("page", "sys.createdAt")
  };
};

const Home = props => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      </main>
    </div>
  );
};

export default Home;
